module CONST
  LOCATION = ['On route', 'In garage'].freeze

  BIKE_MAX_DISTANCE = 30
  BIKE_MAX_WEIGHT = 10
  BIKE_SPEED = 10
  BIKE_COUNT = 10
  BIKE_DELIVERY_COST = 20

  CAR_MAX_WEIGHT = 100
  CAR_SPEED = 50
  CAR_DELIVERY_COST = 100

  MAX_AVAILABLE_WEIGHT = CAR_MAX_WEIGHT
end
